# Generated by Django 2.2 on 2019-04-27 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecog', '0004_auto_20190426_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='DateOfClass',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='studentTookClass',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FaceRecog.Student'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SessionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateOfClass', models.DateTimeField()),
                ('Teacher_Teaches_Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FaceRecog.TeacherTeachesSubject')),
            ],
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='session',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='FaceRecog.SessionRecord'),
            preserve_default=False,
        ),
    ]
