# Generated by Django 2.1.5 on 2019-02-05 22:45

import FaceRecog.models
from django.conf import settings
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateOfClass', models.DateField(auto_now_add=True)),
                ('isPresent', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentTookClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentAttendance', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=6)),
                ('faceData', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='TeacherTeachesSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.CharField(max_length=8)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FaceRecog.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', FaceRecog.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rollNumber', models.CharField(max_length=9, unique=True)),
                ('year', models.CharField(max_length=4)),
                ('presentSemester', models.CharField(choices=[('FrY1', 'First Year, First Semester'), ('FrY2', 'First Year, Second Semester'), ('SeY1', 'Second Year, First Semester'), ('SeY2', 'Second Year, Second Semester'), ('ThY1', 'Third Year, First Semester'), ('ThY2', 'Third Year, Second Semester'), ('FoY1', 'Fourth Year, First Semester'), ('FoY2', 'Fourth Year, Second Semester'), ('FiY1', 'Fifth Year, First Semester'), ('FiY2', 'Fifth Year, Second Semester'), ('XYRp', 'Repeater')], default='FrY1', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='studenttookclass',
            name='Teacher_Teaches_Subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FaceRecog.TeacherTeachesSubject'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='attendance',
            field=models.ManyToManyField(to='FaceRecog.StudentTookClass'),
        ),
        migrations.AddField(
            model_name='teacherteachessubject',
            name='students',
            field=models.ManyToManyField(through='FaceRecog.StudentTookClass', to='FaceRecog.Student'),
        ),
        migrations.AddField(
            model_name='teacherteachessubject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FaceRecog.Teacher'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(through='FaceRecog.TeacherTeachesSubject', to='FaceRecog.Subject'),
        ),
        migrations.AddField(
            model_name='studenttookclass',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FaceRecog.Student'),
        ),
    ]
