# Generated by Django 2.2 on 2019-04-24 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='attendance',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='attendance',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='FaceRecog.StudentTookClass'),
            preserve_default=False,
        ),
    ]
