# Generated by Django 2.2 on 2019-04-24 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecog', '0002_auto_20190425_0222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancerecord',
            old_name='attendance',
            new_name='studentTookClass',
        ),
    ]
