# Generated by Django 2.2 on 2019-04-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecog', '0003_auto_20190425_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='DateOfClass',
            field=models.DateField(),
        ),
    ]
